name: CI build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: docker/setup-qemu-action@v3
      - name: Build and analyze
        run: |
          dotnet test .\ahsoka.sln